networks:
  development_net:

services:

  web_app:
    container_name: '${APP_NAME}-web'
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config/certs:/etc/nginx/certs
      - ./config/web/log:/var/log/nginx
      - ./config/web/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/dev.org
    # entrypoint: [ "/bin/sh", "-c", "chmod +x /opt/src/scripts/initial.sh && sh /opt/src/scripts/initial.sh"]
    # command: /bin/sh -c /opt/src/scripts/initial.sh
    ports:
      - "${APP_PORT}:80"
      - "${APP_TLS_PORT}:443"
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5'
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - development_net

  db_server:
    image: mariadb:10.5.9
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASS
      interval: 5s
      retries: 5
    networks:
      - development_net

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-phpmyadmin'
    ports:
      - '${APP_PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      db_server:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - development_net

volumes:
  db_data:
  db_admin_data:

